export const PRODUCT_LIST_QUERY = 'PRODUCT_LIST_QUERY';
export const COLLCTION_LIST_QUERY = 'COLLCTION_LIST_QUERY';
export const CART_QUERY = 'CART_QUERY';
export const CART_ITEM_COUNT_QUERY = 'CART_ITEM_COUNT_QUERY';
