query getProductList($limit: Int = 12, $after: String, $query: String) {
	products(first: $limit, after: $after, query: $query) {
		edges {
			node {
				id
				handle
				title
				availableForSale
				description(truncateAt: 120)
				priceRange {
					minVariantPrice {
						amount
						currencyCode
					}
				}
				images(first: 1) {
					edges {
						node {
							id
							altText
							transformedSrc
						}
					}
				}
			}
			cursor
		}
		pageInfo {
			hasNextPage
		}
	}
}

query getProductSingle($handle: String!) {
	productByHandle(handle: $handle) {
		title
		description
		descriptionHtml
		availableForSale
		tags
		seo {
			title
			description
		}
		images(first: 250) {
			edges {
				node {
					id
					altText
					transformedSrc
				}
			}
		}
		variants(first: 250) {
			edges {
				node {
					availableForSale
					id
					title
					priceV2 {
						amount
						currencyCode
					}
					image {
						id
					}
				}
			}
		}
	}
}
